### ISSUE TITLE
Seeking contact (and new maintainers for fritzcap)

### ISSUE THREAD

**Issue by jpluimers** [J-Gras/fritz-capture#1]
I found your project via https://boxmatrix.info/wiki/Capture-Projects which has 2 more Python based projects of which fritzcap (https://github.com/jpluimers/fritzcap) which captures VoIP calls and has existed for a very long time (since 2011). I took over the dormant project a few years ago to [solve a few small issues I found](https://github.com/jpluimers/fritzcap/issues?q=is%3Aissue+is%3Aclosed+author%3Ajpluimers) when wanting to use it and [assist in getting other people going](https://github.com/jpluimers/fritzcap/issues?q=is%3Aissue+is%3Aclosed+-author%3Ajpluimers).

Given my health (see https://twitter.com/jpluimers), I have not been able to put effort it since mid 2019, so I am both seeking contact with other Python based Fritz!Box capture projects and at the same time for new fritzcap maintainers.

There is a huge German thread on the IP Phone forum around fritzcap going from [page 1](https://www.ip-phone-forum.de/threads/fritzcap-tool-f%C3%BCr-etherreal-trace-und-audiodaten-extraktion-v2-0.232682/page-2) through [page 24](https://www.ip-phone-forum.de/threads/fritzcap-tool-f%C3%BCr-etherreal-trace-und-audiodaten-extraktion-v2-0.232682/page-24).

I am hardly active there both due to health reasons and my written German not being on par with my German reading skills, but it is a very active and interesting place with ideas for features and solutions with issues/bugs (sometimes even with code suggestions).

If you are interested in cooperation, let me know.

**Comment by J-Gras** [comment]
Hi Jeroen, I am very sorry to hear that you are struggling with your health!

I had a look at the project and it looks very interesting to me. Unfortunately, I am not a user of the FritzBox's phone features. Working on call monitoring will require me to put some effort into a test setup. That being said, I think I can help to maintain the project. I have reached out to you via mail, so we can discuss the details, closing this issue.

**Comment by jpluimers** [comment]
Thanks for the e-mail. Just responded there.
